### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by rcj60560** [zeleven/scallop#1]
Build properties evaluation failed:
- Unable to create properties set 'buildProperties.secrets': file:///G:/githubdemo/scallop/secrets.properties does not exist.
Open File

**Comment by zeleven** [comment]
在根目录下创建个`secrets.properties`文件，并且加入`my_email=xxx@xx.com`就好了，或者把`app`下面`build.gradle`文件中的这段删掉：
```
buildProperties {
    secrets {
        file rootProject.file('secrets.properties')
    }
}
```

**Comment by CuiErNaoAndLiuShanShan** [comment]
我也刚下载了。。。。学习下哈
