### ISSUE TITLE
运行出错。

### ISSUE THREAD

**Issue by chocozhao** [zeleven/scallop#4]
error: cannot find symbol
import io.github.zeleven.scallop.ui.base.BaseFragment;
                                             ^
  symbol:   variable MY_EMAIL
  location: class BuildConfig
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

**Comment by vejei** [comment]
https://github.com/zeleven/scallop/issues/1
